# -*- coding: utf-8 -*-
"""weekly_reports.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BKVQBV7LxTTPdACl2zOl8yiWDt04C06
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import datetime
from datetime import date

df_raw = pd.read_csv('/content/drive/MyDrive/wr.csv')
filt = df_raw['Paid / Organic'] == 'Paid'
df = df_raw[filt]
df

df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

now = pd.Timestamp.now()
first = now.replace(day = 1).normalize()
yday = (now - pd.DateOffset(days=1)).normalize()

first_yoy = (first - pd.DateOffset(years=1)).normalize()
yday_yoy = (yday - pd.DateOffset(years=1)).normalize()

mask = ((df['Date'] >= first) & (df['Date'] <= yday)) | (df['Date'] <= yday_yoy)
df = df.loc[mask]
df

year_grp = df.groupby(['Year'])

impressions = year_grp['Impressions'].sum()
clicks = year_grp['Clicks'].sum()
cost = year_grp['Cost (*)'].sum()
transactions = year_grp['Transactions - UA'].sum()
transaction_revenue = year_grp['Transaction revenue - UA (*)'].sum()

new_df = pd.concat([impressions, clicks, cost, transactions, transaction_revenue], axis='columns', sort=False)
new_df

new_df['CTR'] = (new_df['Clicks'] / new_df['Impressions'])
new_df['CPC'] = (new_df['Cost (*)'] / new_df['Clicks'])
new_df['CPC'] = (new_df['Cost (*)'] / new_df['Clicks'])
new_df['Conversion Rate'] = (new_df['Transactions - UA'] / new_df['Clicks'])
new_df['CPA'] = (new_df['Cost (*)'] / new_df['Transactions - UA'])
new_df['ROAS'] = (new_df['Transaction revenue - UA (*)'] / new_df['Cost (*)'])
new_df

YoY = {}
current_year = date.today().year
previous_year = current_year - 1


for column in new_df:
  cy = new_df.at[current_year, column]
  py = new_df.at[previous_year, column ]
  YoY[column]=((cy - py) / py)

tmp_df = pd.DataFrame(YoY, index=['YoY'])
concat_df = pd.concat([new_df, tmp_df])



"""# New section"""